completed POST topics
Seyaji/be-nc-news-seyaji pull request #4
Opened 2022-02-16 12:06 UTC by Seyaji

completed the code for POST topics and its test

2022-02-16 12:53 UTC, popatre requested changes

2022-02-16 12:53 UTC, popatre commented on __tests__/app.test.js
>           test.concurrent.each(APIPaths)('.get(%s)', (path, expected) => {
I dont know if its somewhere else in the file, but not sure what 'expected' is expected to be. 

i think Vel suggested you dont use the concurrent thing.

2022-02-16 12:53 UTC, popatre commented on __tests__/app.test.js
> +                  description: 'Javascript 101!'
You could also just add another expect to check the length of the topics after. It should be one more added to the length

2022-02-16 13:08 UTC, Seyaji commented on __tests__/app.test.js
> +                  description: 'Javascript 101!'
@popatre how would I go about doing this in the same test without making another request to the API? 
can you provide some guidance on this tomorrow, thanks :)

2022-02-17 11:09 UTC, Augs0 approved these changes
Looks good but consider adding some error handling in this endpoint e.g. what happens if I don't send a slug or description or send another key?

2022-02-17 11:37 UTC, merged